fixing git pre-commit hook
ensure libreum.min.js is minified before accepting commit

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,3 +1,9 @@
 #!/bin/sh
 
-make
+if [ `wc -l js/libreum.min.js | awk '{ print $1 }'` -gt 1 ];
+then
+	echo "js/libreum.min.js not minified.  Aborting commit."
+	exit 1
+fi
+
+make lint
